POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Paulo Correia"
}

###
GET http://localhost:3000/users

###
GET http://localhost:3000/users/0960468c-315b-4ec5-b957-2f12f6e6e0c0